# Generated by Django 5.2.12 on 2026-04-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('link_url', models.URLField(blank=True)),
                ('column', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['column', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('icon_class', models.CharField(max_length=50)),
                ('accent_color', models.CharField(max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('institution', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_label', models.CharField(max_length=50)),
                ('end_label', models.CharField(max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('proficiency', models.CharField(max_length=50)),
                ('icon_class', models.CharField(max_length=50)),
                ('accent_color', models.CharField(max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('about', 'About'), ('resume', 'Resume'), ('services', 'Services'), ('portfolio', 'Portfolio'), ('contact', 'Contact'), ('starter', 'Starter')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['page_key'],
            },
        ),
        migrations.CreateModel(
            name='ProfileHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image_path', models.CharField(default='assets/img/person/person-m-9.webp', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Project categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('icon_class', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
                ('summary_heading', models.CharField(max_length=150)),
                ('summary_text', models.TextField()),
                ('detail_heading', models.CharField(max_length=200)),
                ('detail_intro', models.TextField()),
                ('detail_body', models.TextField()),
                ('detail_footer', models.TextField(blank=True)),
                ('image_path', models.CharField(default='assets/img/services/services-4.webp', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Rashid Zada', max_length=100)),
                ('full_name', models.CharField(max_length=150)),
                ('headline', models.CharField(max_length=255)),
                ('hero_intro', models.CharField(default="I'm", max_length=50)),
                ('about_heading', models.CharField(max_length=255)),
                ('professional_summary', models.TextField()),
                ('about_intro', models.TextField()),
                ('about_body', models.TextField()),
                ('footer_summary', models.TextField()),
                ('career_objective', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('availability', models.CharField(blank=True, max_length=255)),
                ('phone_display', models.CharField(max_length=50)),
                ('phone_link', models.CharField(max_length=50)),
                ('whatsapp_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('portfolio_url', models.URLField()),
                ('github_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('typing_profile_url', models.URLField(blank=True)),
                ('profile_image', models.CharField(default='assets/img/profile-img.jpg', max_length=255)),
                ('hero_background_image', models.CharField(default='assets/img/hero-bg.jpg', max_length=255)),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.PositiveSmallIntegerField()),
                ('column', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['column', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('show_in_hero', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('icon_class', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('icon_class', models.CharField(max_length=50)),
                ('accent_color', models.CharField(max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TypedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='website.experience')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('client', models.CharField(blank=True, max_length=150)),
                ('project_date_label', models.CharField(blank=True, max_length=100)),
                ('project_url', models.URLField(blank=True)),
                ('detail_heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('card_image', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='website.projectcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='website.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='website.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
