# Generated by Django 5.2.12 on 2026-04-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='apple_touch_icon',
            field=models.CharField(default='assets/img/apple-touch-icon.png', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='favicon_image',
            field=models.CharField(default='assets/img/favicon.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='profilehighlight',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
