# Generated by Django 5.2.12 on 2026-04-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_siteconfiguration_apple_touch_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='profile_image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
