# Generated by Django 5.2.12 on 2026-04-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_siteconfiguration_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='assistant_greeting',
            field=models.TextField(default="Assalamualaikum. I am Snail Bot. Ask me about Rashid Zada's profile, skills, services, projects, experience, education, or contact details."),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='assistant_icon',
            field=models.CharField(default='assets/img/site/snail-bot.png', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='assistant_name',
            field=models.CharField(default='Snail Bot', max_length=80),
        ),
    ]
