# Generated by Django 5.2.12 on 2026-04-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_siteconfiguration_assistant_greeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='resume_document',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
