from django.urls import path
from django.views.generic import RedirectView

from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("resume/", views.resume, name="resume"),
    path("services/", views.services, name="services"),
    path("services/details/", views.service_detail_landing, name="service-detail-landing"),
    path("services/<slug:slug>/", views.service_detail, name="service-detail"),
    path("portfolio/", views.portfolio, name="portfolio"),
    path("portfolio/details/", views.portfolio_detail_landing, name="portfolio-detail-landing"),
    path("portfolio/<slug:slug>/", views.portfolio_detail, name="portfolio-detail"),
    path("contact/", views.contact, name="contact"),
    path("contact/submit/", views.contact_form, name="contact-form"),
    path("starter-page/", views.starter_page, name="starter-page"),
    path("api/profile/", views.profile_api, name="api-profile"),
    path("api/site-configuration/", views.site_configuration_api, name="api-site-configuration"),
    path("api/page-intros/", views.page_intro_list_api, name="api-page-intros"),
    path("api/social-links/", views.social_link_list_api, name="api-social-links"),
    path("api/typed-roles/", views.typed_role_list_api, name="api-typed-roles"),
    path("api/about-facts/", views.about_fact_list_api, name="api-about-facts"),
    path("api/statistics/", views.statistic_list_api, name="api-statistics"),
    path("api/skills/", views.skill_list_api, name="api-skills"),
    path("api/certifications/", views.certification_list_api, name="api-certifications"),
    path("api/languages/", views.language_list_api, name="api-languages"),
    path("api/strengths/", views.strength_list_api, name="api-strengths"),
    path("api/profile-highlights/", views.profile_highlight_list_api, name="api-profile-highlights"),
    path("api/education/", views.education_list_api, name="api-education"),
    path("api/experiences/", views.experience_list_api, name="api-experiences"),
    path("api/services/", views.service_list_api, name="api-services"),
    path("api/services/<slug:slug>/", views.service_detail_api, name="api-service-detail"),
    path("api/project-categories/", views.project_category_list_api, name="api-project-categories"),
    path("api/projects/", views.project_list_api, name="api-projects"),
    path("api/projects/<slug:slug>/", views.project_detail_api, name="api-project-detail"),
    path("api/snail-bot/chat/", views.snail_bot_chat_api, name="api-snail-bot-chat"),
    path("index.html", RedirectView.as_view(pattern_name="home", permanent=True)),
    path("about.html", RedirectView.as_view(pattern_name="about", permanent=True)),
    path("resume.html", RedirectView.as_view(pattern_name="resume", permanent=True)),
    path("services.html", RedirectView.as_view(pattern_name="services", permanent=True)),
    path("service-details.html", views.service_detail_landing, name="legacy-service-detail"),
    path("portfolio.html", RedirectView.as_view(pattern_name="portfolio", permanent=True)),
    path("portfolio-details.html", views.portfolio_detail_landing, name="legacy-portfolio-detail"),
    path("contact.html", RedirectView.as_view(pattern_name="contact", permanent=True)),
    path("starter-page.html", RedirectView.as_view(pattern_name="starter-page", permanent=True)),
    path("forms/contact.php", views.contact_form, name="legacy-contact-form"),
]
